language: go

go:
  - master
  
before_install:
    - go get -t -v ./...
    
install:
    - CGO_ENABLED=0 GO111MODULE=on go get github.com/Sherlock-Holo/camouflage

script:
    - CGO_ENABLED=0 GO111MODULE=on go build -v .
