[client]
type = "quic"

host = "camouflage.example.com:9876"
path = "/"

# set a ca to debug camouflage, non-recommand use in product server (optional)
debug_ca = "script/ca/ca.crt"

listen_addr = "127.0.0.1:9875"

# handshake timeout (optional)
timeout = "30s"

# TOTP secret
secret = "V5PWBWKLNKOSGQIIB2J2GLIAMSS4IGQJ"
period = 60


[server]
type = "quic"

host = "camouflage.example.com"
path = "/"

listen_addr = "127.0.0.1:9876"

key = "script/server/server.key"
crt = "script/server/server.crt"

# serve a static web site (optional)
web_root = "/home/sherlock/git/blog/public"

# sni feature for web service (optional)
web_host = "blog.example.com"
web_key = "script/web/web.key"
web_crt = "script/web/web.crt"

# handshake timeout (optional)
timeout = "30s"

# TOTP secret
secret = "V5PWBWKLNKOSGQIIB2J2GLIAMSS4IGQJ"
period = 60

# reverse proxy (optional)
reverse_proxy_host = "rp.example.com"
reverse_proxy_key = "script/rp/rp.key"
reverse_proxy_crt = "script/rp/rp.crt"
reverse_proxy_addr = "127.0.0.1:80"