[client]
remote_addr = "127.0.0.1"
remote_port = 9876
path = "/websocket"

ca_crt = "../script/ca/ca.crt"

crt = "../script/client/client.crt"
key = "../script/client/client.key"

    [client.ss]
    type = "ss"
    max_links = 100
    listen_addr = "127.0.0.1"
    listen_port = 9876
    key = "holo"

    [client.socks]
    type = "socks"
    max_links = 100
    listen_addr = "127.0.0.1"
    listen_port = 9875


[server]
bind_addr = "127.0.0.1"
bind_port = 9876
path = "/websocket"

ca_crt = "../script/ca/ca.crt"

crt = "../script/server/server.crt"
key = "../script/server/server.key"

dns = "udp#119.29.29.29:53"