[client]
remote_addr = "camouflage.example.com:9876"

# set a ca to debug camouflage, non-recommand use in product server (optional)
debug_ca = "script/ca/ca.crt"

listen_addr = "127.0.0.1:9875"

# handshake timeout (optional)
timeout = "30s"

# TOTP secret
secret = "V5PWBWKLNKOSGQIIB2J2GLIAMSS4IGQJ"
period = 60


[server]
host = "camouflage.example.com:9876"

listen_addr = "127.0.0.1:9876"

key = "script/server/server.key"
crt = "script/server/server.crt"

# serve a static web site (optional)
web_root = "/home/sherlock/git/blog/public"

# sni feature for web service (optional)
web_host = "blog.example.com:9876"
web_key = "script/web/web.key"
web_crt = "script/web/web.crt"

# handshake timeout (optional)
timeout = "30s"

# TOTP secret
secret = "V5PWBWKLNKOSGQIIB2J2GLIAMSS4IGQJ"
period = 60