# new auth type
token = "HmKThr6ZQUeIXl12CVTXnOLJ0bA0ow-BqLOWjwYDhNs"

[client]
remote_addr = "127.0.0.1"
remote_port = 9876
path = "/websocket"

max_links = 100

# if use self-signed certificate, un-comment to import self CA
self_ca = "../script/ca/ca.crt"

# un-comment to enable monitor
#monitor_addr = "127.0.0.1"
#monitor_port = 19998

    [client.ss]
    type = "ss"
    listen_addr = "127.0.0.1"
    listen_port = 9877
    key = "holo"

    [client.socks]
    type = "socks"
    listen_addr = "127.0.0.1"
    listen_port = 9875


[server]
dns_type = "udp"
dns = "119.29.29.29:53"


[server.camouflage]
type = "camouflage"

host = "camouflage.example.com"

listen_addr = "127.0.0.1"
listen_port = 9876

crt = "../script/server/server.crt"
key = "../script/server/server.key"

token = "HmKThr6ZQUeIXl12CVTXnOLJ0bA0ow-BqLOWjwYDhNs"
path = "/websocket"

web_root = "test"

[server.web]
type = "web"

host = "www.example.com"

listen_addr = "127.0.0.1"
listen_port = 9876

crt = "../script/server/server.crt"
key = "../script/server/server.key"

web_root = "test2"


[server.web2]
type = "web"

host = "test.example.com"

listen_addr = "127.0.0.1"
listen_port = 9875

crt = "../script/server/server.crt"
key = "../script/server/server.key"

web_root = ""